version: '3'

services:
  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - "./Prometheus Data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./alert.rules.yml:/etc/prometheus/alert.rules.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - "./Grafana Data:/var/lib/grafana"

  springbootmetrics:
    build: ./SpringBootMetrics
    container_name: springbootmetrics
    ports:
      - "8080:8080"
    networks:
      - monitoring
      
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring
    volumes:
          - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
          - "./slack_url:/etc/alertmanager/slack_url"

networks:
  monitoring: