version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - "./Prometheus Data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - "./Grafana Data:/var/lib/grafana"

  springbootmetrics:
    build: ./SpringBootMetrics
    container_name: springbootmetrics
    ports:
      - "8080:8080"
    networks:
      - monitoring

networks:
  monitoring: