scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springbootmetrics:8080']
      
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
  
rule_files:
  - 'alert.rules.yml'
